### ISSUE TITLE
Search is terrible and useless

### ISSUE THREAD

**Issue by agilbertson1977** [SoylentNews/slashcode#373] opened 2014-10-22 14:57 UTC
Here's a bug for you:  results are returned when you search for "Andrea Rossi": http://soylentnews.org/search.pl?tid=&query=Andrea+Rossi&author=&sort=1&op=stories
but no results are returned when you search for "E Cat", "E-Cat", "(E-Cat)", or "(E cat)", despite the string "(E-Cat)" being in the story about Andrea Rossi's device.

**Comment by cookjj** [comment] 2015-02-01 17:34
I think this is a legacy pain-in-the-A from Slashdot which, personally, I've alwasy found useless. Just duckduckgo your search but limit it to soylentnews.org :) MIght take a serious re-implementation to fix this bug.

**Comment by TheMightyBuzzard** [comment] 2015-02-01 17:37
cookjj: you're not wrong.

**Comment by NCommander** [comment] 2015-03-13 22:56
Duplicate of #17 closing this one out.

**Closed by NCommander** 2015-03-13 22:56 UTC
