### ISSUE TITLE
Story Preview label padding-top issue

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/slashcode#440] opened 2015-04-13 00:19 UTC
Google Chrome, Windows
mrcoolbp can confirm this issue

The 1em of padding-top given to label elements seems to be obscuring other elements.

For example it is difficult to click on the input element that holds the publishing timestamp, because the padding from the "Link Story to Existing Poll" label is obscuring it. You can't click on part of that link because the padding from "Attach File" is obscuring that.

Getting rid of "padding: 1em 0 0 0;" added to all label elements solved the issue:

admin.pl
base.css?slashcode_15_03
block starting on line 868

label
{
display: block;
font-weight: bold;
padding: 1em 0 0 0;
}

label
{
display: block;
font-weight: bold;
/* padding: 1em 0 0 0; */
}

**Comment by paulej72** [comment] 2015-04-13 13:19
Wow, the code on the story edit page is just crap.  I never realized how bad some of this was.  I think the issue is to fix the broken page layout first then I’ll see if a css fix is need.  Was this issue happening elsewhere?

**Comment by soytakyon** [comment] 2015-04-15 04:02
A label will make it impossible to click anything 1em above it, at least on Chrome. It's why I mentioned the links, they are inside label elements that cover up the links above them and the input type="text" box.

**Comment by paulej72** [comment] 2015-04-24 15:38
Fixed in #443

**Closed by paulej72** 2015-04-24 15:38 UTC
